spring:
  datasource:
    url: jdbc:h2:file:./data/networkdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

network:
  scan-interval: 300000  # 5分钟
  metrics-interval: 60000  # 1分钟 